# Generated by Django 5.0.3 on 2024-03-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0003_acessomedico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessomedico',
            name='token',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
